### ISSUE TITLE
(WIP) Not working

### ISSUE THREAD

**Issue by qasid2k** [jameslinimk/chess-com-cheater#1]
I just get this error whenever i press start hack 
I'm using mozilla and this happened after i updated the extension
![error chesss cheat](https://user-images.githubusercontent.com/128454513/233828299-8d85ae55-4af4-48d7-9a15-796446abac36.PNG)

**Comment by RED-ux101** [comment]
same

**Comment by jameslinimk** [comment]
> I just get this error whenever i press start hack I'm using mozilla and this happened after i updated the extension ![error chesss cheat](https://user-images.githubusercontent.com/128454513/233828299-8d85ae55-4af4-48d7-9a15-796446abac36.PNG)

Hmm, let me see. Ill push a fix in a few hours. For now, just use the previous version

**Comment by jameslinimk** [comment]
Are you guys using the firefox/chrome store release or the github one?

**Comment by Patjwmiller** [comment]
Building from source, same problem. I'll revert if needed. I'll check into what might have broke things.

**Comment by Patjwmiller** [comment]
the extension on chrome works though. The one from the chrome store I mean.

**Comment by qasid2k** [comment]
> 

On mozilla, i tried both the mozilla realease and the github one but face the same issue

**Comment by jameslinimk** [comment]
I know the issue. If you run the dev script (without terser) it works. I'm working on js scripts instead of cli ones. Should be pushed tn

**Comment by Patjwmiller** [comment]
> I know the issue. If you run the dev script (without terser) it works. I'm working on js scripts instead of cli ones. Should be pushed tn

trying to minify JavaScript code to improve some performance I'm assuming? Should be good though.

**Comment by RED-ux101** [comment]
what happened to updating it 2 days ago 😭

**Comment by Patjwmiller** [comment]
> what happened to updating it 2 days ago 😭

if you need it to absolutely work, use the chrome extension on the store, or if you're building it yourself from source, remove "        "terser": "^5.17.0"," from the package.json file and re-build.

**Comment by jameslinimk** [comment]
So sorry, everyone for the wait. I just came back from a big testing week at school, should be fixed. Firefox & chrome are awaiting changes.
